/*

* two or more functions declared with the same name - arguments should differn in type and/or number
* for pointers and reference arguments qualifiers participate in overloading. - this is nor the case for other arguments
* return type is ignored for overloading
* different implementations of the same behavior
* resolve at compil;e time - static polymorphism
* 
* 
* name mangling:
*		+ unique names generated by the compiler
*		+ allows linker to link the call with the correct overloaded function
*		- depends on compiler, varies from compiler to compiler
*		- depends on the tyoe and number of the function arguments
*		- c++ functions arenot callable from C code
* 

*/